//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPaint {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyPaint.LocalizedResources", typeof(LocalizedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to credits.
        /// </summary>
        public static string ButtonCreditsText {
            get {
                return ResourceManager.GetString("ButtonCreditsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string ButtonSettingsText {
            get {
                return ResourceManager.GetString("ButtonSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start game.
        /// </summary>
        public static string ButtonStartText {
            get {
                return ResourceManager.GetString("ButtonStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Africa.
        /// </summary>
        public static string group_Africa {
            get {
                return ResourceManager.GetString("group_Africa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America.
        /// </summary>
        public static string group_America {
            get {
                return ResourceManager.GetString("group_America", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe.
        /// </summary>
        public static string group_Europe {
            get {
                return ResourceManager.GetString("group_Europe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oceania.
        /// </summary>
        public static string group_Oceania {
            get {
                return ResourceManager.GetString("group_Oceania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kangaroo.
        /// </summary>
        public static string item_canguro {
            get {
                return ResourceManager.GetString("item_canguro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crocodile.
        /// </summary>
        public static string item_coccodrillo {
            get {
                return ResourceManager.GetString("item_coccodrillo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasmanian devil.
        /// </summary>
        public static string item_diavolo {
            get {
                return ResourceManager.GetString("item_diavolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gazelle.
        /// </summary>
        public static string item_gazzella {
            get {
                return ResourceManager.GetString("item_gazzella", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to koala.
        /// </summary>
        public static string item_koala {
            get {
                return ResourceManager.GetString("item_koala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lion.
        /// </summary>
        public static string item_lion {
            get {
                return ResourceManager.GetString("item_lion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rhinoceros.
        /// </summary>
        public static string item_rinoceronte {
            get {
                return ResourceManager.GetString("item_rinoceronte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meerkats.
        /// </summary>
        public static string item_suricati {
            get {
                return ResourceManager.GetString("item_suricati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tiger.
        /// </summary>
        public static string item_tiger {
            get {
                return ResourceManager.GetString("item_tiger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zebra.
        /// </summary>
        public static string item_zebra {
            get {
                return ResourceManager.GetString("item_zebra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to level completed!.
        /// </summary>
        public static string message_level_completed {
            get {
                return ResourceManager.GetString("message_level_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to level failed!.
        /// </summary>
        public static string message_level_failed {
            get {
                return ResourceManager.GetString("message_level_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        public static string MsgBoxExit {
            get {
                return ResourceManager.GetString("MsgBoxExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MsgBoxTitleWarning {
            get {
                return ResourceManager.GetString("MsgBoxTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to water.
        /// </summary>
        public static string water {
            get {
                return ResourceManager.GetString("water", resourceCulture);
            }
        }
    }
}
