//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPaint {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyPaint.LocalizedResources", typeof(LocalizedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby Looney toones.
        /// </summary>
        internal static string baby_looney_toones {
            get {
                return ResourceManager.GetString("baby_looney_toones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Beauty and the Beast.
        /// </summary>
        internal static string beauty_beast {
            get {
                return ResourceManager.GetString("beauty_beast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow White.
        /// </summary>
        internal static string biancaneve {
            get {
                return ResourceManager.GetString("biancaneve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caillou.
        /// </summary>
        internal static string caillou {
            get {
                return ResourceManager.GetString("caillou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars.
        /// </summary>
        internal static string cars {
            get {
                return ResourceManager.GetString("cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tom And Jerry.
        /// </summary>
        internal static string tom_and_jerry {
            get {
                return ResourceManager.GetString("tom_and_jerry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toy Story.
        /// </summary>
        internal static string toy_story {
            get {
                return ResourceManager.GetString("toy_story", resourceCulture);
            }
        }
    }
}
