//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPaint {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyPaint.LocalizedResources", typeof(LocalizedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to credits.
        /// </summary>
        public static string ButtonCreditsText {
            get {
                return ResourceManager.GetString("ButtonCreditsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string ButtonHelpText {
            get {
                return ResourceManager.GetString("ButtonHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to easy.
        /// </summary>
        public static string ButtonLevelEasyText {
            get {
                return ResourceManager.GetString("ButtonLevelEasyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hard.
        /// </summary>
        public static string ButtonLevelHardText {
            get {
                return ResourceManager.GetString("ButtonLevelHardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medium.
        /// </summary>
        public static string ButtonLevelMediumText {
            get {
                return ResourceManager.GetString("ButtonLevelMediumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string ButtonSettingsText {
            get {
                return ResourceManager.GetString("ButtonSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play!.
        /// </summary>
        public static string ButtonStartArcadeText {
            get {
                return ResourceManager.GetString("ButtonStartArcadeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gallery.
        /// </summary>
        public static string ButtonStartGalleryText {
            get {
                return ResourceManager.GetString("ButtonStartGalleryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App engineering: Davide Tentori
        ///Graphics and clipart: virinaflora - Fotolia.com, Marta&amp;Martina
        ///Background music / sound fx: Raphael Ruis
        ///
        ///Very special thanks to: Isa, Ele, Albi, Luca for moral and technical support!
        ///
        ///Special thanks to Marco Uberti for inspiration of this game. 
        ///Checkout his awesome apps at www.invenktion.it.
        /// </summary>
        public static string CreditsPage_MainText {
            get {
                return ResourceManager.GetString("CreditsPage_MainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREDITS.
        /// </summary>
        public static string CreditsPage_MainTitle {
            get {
                return ResourceManager.GetString("CreditsPage_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to score:.
        /// </summary>
        public static string DrawScore {
            get {
                return ResourceManager.GetString("DrawScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection not available, please retry.
        /// </summary>
        public static string Error_NoNetworkAvailable {
            get {
                return ResourceManager.GetString("Error_NoNetworkAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occurred the last time you ran this app :(
        ///Would you like to send an email to report it?.
        /// </summary>
        public static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem report.
        /// </summary>
        public static string ExceptionMessageTitle {
            get {
                return ResourceManager.GetString("ExceptionMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Your feedback here]
        ///
        ///
        ///---------------------------------
        ///Device Name: {0}
        ///Device Manufacturer: {1}
        ///Device Firmware Version: {2}
        ///Device Hardware Version: {3}
        ///Application Version: {4}
        ///---------------------------------.
        /// </summary>
        public static string FeedbackBody {
            get {
                return ResourceManager.GetString("FeedbackBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry to hear you didn&apos;t want to rate this app.
        ///
        ///Tell us about your experience or suggest how we can make it even better :).
        /// </summary>
        public static string FeedbackMessage1 {
            get {
                return ResourceManager.GetString("FeedbackMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no thanks.
        /// </summary>
        public static string FeedbackNo {
            get {
                return ResourceManager.GetString("FeedbackNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; feedback/comment .
        /// </summary>
        public static string FeedbackOrCommentText {
            get {
                return ResourceManager.GetString("FeedbackOrCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can we make it better?.
        /// </summary>
        public static string FeedbackTitle {
            get {
                return ResourceManager.GetString("FeedbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to give feedback.
        /// </summary>
        public static string FeedbackYes {
            get {
                return ResourceManager.GetString("FeedbackYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full.
        /// </summary>
        public static string FullVersion {
            get {
                return ResourceManager.GetString("FullVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train yourself colouring all animals!.
        /// </summary>
        public static string GalleryPage_InfoText_Purchased {
            get {
                return ResourceManager.GetString("GalleryPage_InfoText_Purchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Africa.
        /// </summary>
        public static string group_Africa {
            get {
                return ResourceManager.GetString("group_Africa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America.
        /// </summary>
        public static string group_America {
            get {
                return ResourceManager.GetString("group_America", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antartica.
        /// </summary>
        public static string group_Antarctica {
            get {
                return ResourceManager.GetString("group_Antarctica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia.
        /// </summary>
        public static string group_Asia {
            get {
                return ResourceManager.GetString("group_Asia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe.
        /// </summary>
        public static string group_Europe {
            get {
                return ResourceManager.GetString("group_Europe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oceania.
        /// </summary>
        public static string group_Oceania {
            get {
                return ResourceManager.GetString("group_Oceania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONGRATULATIONS! All animals of continent {0} completed! Now let&apos;s discover {1}!.
        /// </summary>
        public static string GroupCompleted {
            get {
                return ResourceManager.GetString("GroupCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us!.
        /// </summary>
        public static string HelpPage_ButtonContactUsText {
            get {
                return ResourceManager.GetString("HelpPage_ButtonContactUsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw at least 70% of each picture to unlock and access new animals and continents! 
        ///Be accurate, be precise but... be FAST!.
        /// </summary>
        public static string HelpPage_HelpMainText {
            get {
                return ResourceManager.GetString("HelpPage_HelpMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP.
        /// </summary>
        public static string HelpPage_HelpMainTitle {
            get {
                return ResourceManager.GetString("HelpPage_HelpMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions/feedback?.
        /// </summary>
        public static string HelpPage_NeedHelpQuestionText {
            get {
                return ResourceManager.GetString("HelpPage_NeedHelpQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate 5 stars!!!.
        /// </summary>
        public static string HelpPage_RateThisGameButtonText {
            get {
                return ResourceManager.GetString("HelpPage_RateThisGameButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you like this game?.
        /// </summary>
        public static string HelpPage_RateThisGameRequestText {
            get {
                return ResourceManager.GetString("HelpPage_RateThisGameRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to albatross.
        /// </summary>
        public static string item_albatro {
            get {
                return ResourceManager.GetString("item_albatro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elk.
        /// </summary>
        public static string item_alce {
            get {
                return ResourceManager.GetString("item_alce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eagle.
        /// </summary>
        public static string item_aquila {
            get {
                return ResourceManager.GetString("item_aquila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to armadillo.
        /// </summary>
        public static string item_armadillo {
            get {
                return ResourceManager.GetString("item_armadillo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vulture.
        /// </summary>
        public static string item_avvoltoio {
            get {
                return ResourceManager.GetString("item_avvoltoio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whale.
        /// </summary>
        public static string item_balena {
            get {
                return ResourceManager.GetString("item_balena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bison.
        /// </summary>
        public static string item_bisonte {
            get {
                return ResourceManager.GetString("item_bisonte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sloath.
        /// </summary>
        public static string item_bradipo {
            get {
                return ResourceManager.GetString("item_bradipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to camel.
        /// </summary>
        public static string item_cammello {
            get {
                return ResourceManager.GetString("item_cammello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dog.
        /// </summary>
        public static string item_cane {
            get {
                return ResourceManager.GetString("item_cane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kangaroo.
        /// </summary>
        public static string item_canguro {
            get {
                return ResourceManager.GetString("item_canguro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deer.
        /// </summary>
        public static string item_cervo {
            get {
                return ResourceManager.GetString("item_cervo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frilled lizard.
        /// </summary>
        public static string item_clamidosauro {
            get {
                return ResourceManager.GetString("item_clamidosauro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cobra.
        /// </summary>
        public static string item_Cobra {
            get {
                return ResourceManager.GetString("item_Cobra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crocodile.
        /// </summary>
        public static string item_coccodrillo {
            get {
                return ResourceManager.GetString("item_coccodrillo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tasmanian devil.
        /// </summary>
        public static string item_diavolo {
            get {
                return ResourceManager.GetString("item_diavolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elephant.
        /// </summary>
        public static string item_elefante {
            get {
                return ResourceManager.GetString("item_elefante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indian elephant.
        /// </summary>
        public static string item_elefante_indiano {
            get {
                return ResourceManager.GetString("item_elefante_indiano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elephant seal.
        /// </summary>
        public static string item_elefantemarino {
            get {
                return ResourceManager.GetString("item_elefantemarino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seal.
        /// </summary>
        public static string item_foca {
            get {
                return ResourceManager.GetString("item_foca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ant-bear.
        /// </summary>
        public static string item_formichiere {
            get {
                return ResourceManager.GetString("item_formichiere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cat.
        /// </summary>
        public static string item_gatto {
            get {
                return ResourceManager.GetString("item_gatto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gazelle.
        /// </summary>
        public static string item_gazzella {
            get {
                return ResourceManager.GetString("item_gazzella", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to giraffe.
        /// </summary>
        public static string item_giraffa {
            get {
                return ResourceManager.GetString("item_giraffa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hyppo.
        /// </summary>
        public static string item_ippopotamo {
            get {
                return ResourceManager.GetString("item_ippopotamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to koala.
        /// </summary>
        public static string item_koala {
            get {
                return ResourceManager.GetString("item_koala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lion.
        /// </summary>
        public static string item_leone {
            get {
                return ResourceManager.GetString("item_leone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hare.
        /// </summary>
        public static string item_lepre {
            get {
                return ResourceManager.GetString("item_lepre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to marmot.
        /// </summary>
        public static string item_marmotta {
            get {
                return ResourceManager.GetString("item_marmotta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grampus.
        /// </summary>
        public static string item_orca {
            get {
                return ResourceManager.GetString("item_orca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bear.
        /// </summary>
        public static string item_orso {
            get {
                return ResourceManager.GetString("item_orso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to white bear.
        /// </summary>
        public static string item_orsobianco {
            get {
                return ResourceManager.GetString("item_orsobianco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to panda.
        /// </summary>
        public static string item_panda {
            get {
                return ResourceManager.GetString("item_panda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clown fish.
        /// </summary>
        public static string item_pesce_pagliaccio {
            get {
                return ResourceManager.GetString("item_pesce_pagliaccio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to penguin.
        /// </summary>
        public static string item_pinguino {
            get {
                return ResourceManager.GetString("item_pinguino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reindeer.
        /// </summary>
        public static string item_renna {
            get {
                return ResourceManager.GetString("item_renna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hedgehog.
        /// </summary>
        public static string item_riccio {
            get {
                return ResourceManager.GetString("item_riccio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rhinoceros.
        /// </summary>
        public static string item_rinoceronte {
            get {
                return ResourceManager.GetString("item_rinoceronte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monkey.
        /// </summary>
        public static string item_scimmietta {
            get {
                return ResourceManager.GetString("item_scimmietta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to squirrel.
        /// </summary>
        public static string item_scoiattolo {
            get {
                return ResourceManager.GetString("item_scoiattolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meerkats.
        /// </summary>
        public static string item_suricati {
            get {
                return ResourceManager.GetString("item_suricati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flatback sea turtle.
        /// </summary>
        public static string item_tartaruga {
            get {
                return ResourceManager.GetString("item_tartaruga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tiger.
        /// </summary>
        public static string item_tiger {
            get {
                return ResourceManager.GetString("item_tiger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tiger.
        /// </summary>
        public static string item_Tigre {
            get {
                return ResourceManager.GetString("item_Tigre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fox.
        /// </summary>
        public static string item_volpe {
            get {
                return ResourceManager.GetString("item_volpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yak.
        /// </summary>
        public static string item_Yak {
            get {
                return ResourceManager.GetString("item_Yak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zebra.
        /// </summary>
        public static string item_zebra {
            get {
                return ResourceManager.GetString("item_zebra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select game difficulty.
        /// </summary>
        public static string LevelSelectionHeader {
            get {
                return ResourceManager.GetString("LevelSelectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to level completed!.
        /// </summary>
        public static string message_level_completed {
            get {
                return ResourceManager.GetString("message_level_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to level failed!.
        /// </summary>
        public static string message_level_failed {
            get {
                return ResourceManager.GetString("message_level_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONGRATULATIONS!!! All levels completed!!!.
        /// </summary>
        public static string MessageAllLevelsCompleted {
            get {
                return ResourceManager.GetString("MessageAllLevelsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        public static string MsgBoxExit {
            get {
                return ResourceManager.GetString("MsgBoxExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MsgBoxTitleWarning {
            get {
                return ResourceManager.GetString("MsgBoxTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to score:.
        /// </summary>
        public static string PainterPageCurrentScore {
            get {
                return ResourceManager.GetString("PainterPageCurrentScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record:.
        /// </summary>
        public static string PainterPageRecord {
            get {
                return ResourceManager.GetString("PainterPageRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;d love you to rate our app 5 stars :)
        ///
        ///Showing us some love on the store helps us to continue to work on the app and make things even better!.
        /// </summary>
        public static string RatingMessage1 {
            get {
                return ResourceManager.GetString("RatingMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You look to be getting a lot of use out of our app!
        ///
        ///Why not give us a 5 star rating to show your appreciation?.
        /// </summary>
        public static string RatingMessage2 {
            get {
                return ResourceManager.GetString("RatingMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no thanks.
        /// </summary>
        public static string RatingNo {
            get {
                return ResourceManager.GetString("RatingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoying {0}?.
        /// </summary>
        public static string RatingTitle {
            get {
                return ResourceManager.GetString("RatingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate 5 stars.
        /// </summary>
        public static string RatingYes {
            get {
                return ResourceManager.GetString("RatingYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time bonus:.
        /// </summary>
        public static string TimeScore {
            get {
                return ResourceManager.GetString("TimeScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total:.
        /// </summary>
        public static string TotalScore {
            get {
                return ResourceManager.GetString("TotalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but you need full version to play with all items, do you want to get it?.
        /// </summary>
        public static string Trial_ArcadeGameLimitation {
            get {
                return ResourceManager.GetString("Trial_ArcadeGameLimitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but gallery pictures are available only into full version, do you want to get it?.
        /// </summary>
        public static string Trial_GalleryAvailableOnlyIntoFullVersion {
            get {
                return ResourceManager.GetString("Trial_GalleryAvailableOnlyIntoFullVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trial.
        /// </summary>
        public static string TrialVersion {
            get {
                return ResourceManager.GetString("TrialVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to quit app?.
        /// </summary>
        public static string WarningExit {
            get {
                return ResourceManager.GetString("WarningExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Yes if you’d like to use this app’s background music (this will stop your current music playback).
        /// </summary>
        public static string WarningMusic {
            get {
                return ResourceManager.GetString("WarningMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to water.
        /// </summary>
        public static string water {
            get {
                return ResourceManager.GetString("water", resourceCulture);
            }
        }
    }
}
